### ISSUE TITLE
Get all issues

### ISSUE THREAD

**Issue by camlafit** [testmonitor/mantis-client#8]
By default mantis api limit issues listing to 50 results.
https://documenter.getpostman.com/view/29959/mantis-bug-tracker-rest-api/7Lt6zkP#73397753-1560-a5cb-45f0-e0ce0194ceca

Could be interessting to have by default all issues or provide option to manage pagination results.

**Comment by stefanius** [comment]
Thank you for this issue. We already discussed some in the PR. This issue is fixed in https://github.com/testmonitor/mantis-client/pull/10
